/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package A_tictactoe;

import org.junit.Test;
import static org.junit.Assert.*;

public class tictactoeTest {
    @Test public void testAppHasAGreeting() {
        tictactoe classUnderTest = new tictactoe();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
